const Client = require('../models/Client');

// Helper: consistent success response
function success(res, message, data) {
  return res.json({ success: true, message, data });
}

// Helper: validation error
function validationError(res, message, errors) {
  return res.status(400).json({ success: false, message, errors });
}

// Helper: not found
function notFound(res, message) {
  return res.status(404).json({ success: false, message });
}

// Helper: server error
function serverError(res, message) {
  return res.status(500).json({ success: false, message });
}

exports.createClient = async (req, res) => {
  try {
    const { name, description, status } = req.body;
    if (!name || !String(name).trim()) {
      return validationError(res, 'Validation error', { name: 'Name is required' });
    }

    if (status && !['active', 'inactive'].includes(status)) {
      return validationError(res, 'Validation error', { status: 'Invalid status' });
    }

    // Check name uniqueness among non-deleted
    const existing = await Client.findOne({ name: name.trim(), isDeleted: false }).lean().exec();
    if (existing) return validationError(res, 'Validation error', { name: 'Name must be unique' });

    const client = new Client({ name: name.trim(), description, status });
    await client.save();
    return success(res, 'Client created', client);
  } catch (err) {
    if (err.name === 'ValidationError') return validationError(res, 'Validation error', { error: err.message });
    console.error(err);
    return serverError(res, 'Server error');
  }
};

exports.getClients = async (req, res) => {
  try {
    const clients = await Client.find({ isDeleted: false }).sort({ createdAt: -1 }).lean().exec();
    return success(res, 'Clients retrieved', clients);
  } catch (err) {
    console.error(err);
    return serverError(res, 'Server error');
  }
};

exports.getClientById = async (req, res) => {
  try {
    const { id } = req.params;
    const client = await Client.findOne({ _id: id, isDeleted: false }).lean().exec();
    if (!client) return notFound(res, 'Client not found');
    return success(res, 'Client retrieved', client);
  } catch (err) {
    console.error(err);
    return serverError(res, 'Server error');
  }
};

exports.updateClient = async (req, res) => {
  try {
    const { id } = req.params;
    const { name, description, status } = req.body;

    const client = await Client.findOne({ _id: id, isDeleted: false }).exec();
    if (!client) return notFound(res, 'Client not found');

    if (name !== undefined) {
      if (!String(name).trim()) return validationError(res, 'Validation error', { name: 'Name cannot be empty' });
      // Check uniqueness among non-deleted
      const existing = await Client.findOne({ name: name.trim(), isDeleted: false, _id: { $ne: id } }).lean().exec();
      if (existing) return validationError(res, 'Validation error', { name: 'Name must be unique' });
      client.name = name.trim();
      // slug will be regenerated by pre-validate hook
    }

    if (description !== undefined) client.description = description;
    if (status !== undefined) {
      if (!['active', 'inactive'].includes(status)) return validationError(res, 'Validation error', { status: 'Invalid status' });
      client.status = status;
    }

    await client.save();
    return success(res, 'Client updated', client);
  } catch (err) {
    if (err.name === 'ValidationError') return validationError(res, 'Validation error', { error: err.message });
    console.error(err);
    return serverError(res, 'Server error');
  }
};

exports.deleteClient = async (req, res) => {
  try {
    const { id } = req.params;
    const client = await Client.findOne({ _id: id, isDeleted: false }).exec();
    if (!client) return notFound(res, 'Client not found');
    client.isDeleted = true;
    await client.save();
    return success(res, 'Client deleted', null);
  } catch (err) {
    console.error(err);
    return serverError(res, 'Server error');
  }
};
